//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Papizz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meny
    {
        public int Id { get; set; }
        public string Namn { get; set; }
        public decimal Pris { get; set; }
        public string Topping { get; set; }
    }
}
